### ISSUE TITLE
Номер аудиторії не відображається

### ISSUE THREAD

**Issue by ValeryP** [kpi-ua/ecampus-client-android#13]
![photo_2015-01-19_15-46-16](https://cloud.githubusercontent.com/assets/3534020/5801322/6adc4b90-9ff2-11e4-970e-2d5a6daba45f.jpg)

**Comment by Deepnekroz** [comment]
Is it problem appear at http://rozklad.org.ua/ ?

**Comment by ValeryP** [comment]
Так, в таких випадках замість "-18" краще відображати "18к". 
-18 можна поплутати з температурою в корпусі ;)

**Comment by doroshartyom** [comment]
@ValeryP we will fix this in next pre-release.
