### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by infm** [kpi-ua/ecampus-client-android#4]
Каким образом должна осуществляться обратная связь? Через e-mail?

**Comment by doroshartyom** [comment]
Feedback will be working or over email or over own API. Also we can use built-in reporter and send it to GPDC (Google Play Dev Console).

**Comment by infm** [comment]
@Deepnekroz if it's only the crash reporter, I'd suggest using [Crashlytics](https://crashlytics.com)
I'll implement sending email through simple mailto: for now
