### ISSUE TITLE
Invisible titles of input areas while not active

### ISSUE THREAD

**Issue by kingracer** [kpi-ua/ecampus-client-android#52]
![screenshot_20160622-170745](https://cloud.githubusercontent.com/assets/8422318/16269767/5ffc6f0e-389c-11e6-8635-a160959c97ca.png)
![screenshot_20160622-170749](https://cloud.githubusercontent.com/assets/8422318/16269776/6d8fce90-389c-11e6-872d-1481664aae08.png)
On this screenshots showed that first and second row showing titles while active only.

**Comment by floring** [comment]
Fixed in ed7543af4d225e0ba3b56c7e5042752165d06a4f.
