### ISSUE TITLE
Human readable format for date values

### ISSUE THREAD

**Issue by ernado-x** [kpi-ua/ecampus-client-android#53]
Please, use human readable format for date values
For example: 2016/05/14

![default](https://cloud.githubusercontent.com/assets/3822922/16299782/b7b3dc3e-3944-11e6-9c42-3aa3a7aac398.PNG)
![2](https://cloud.githubusercontent.com/assets/3822922/16299783/b7b3e59e-3944-11e6-8530-5e8c87d188cd.PNG)

**Comment by floring** [comment]
Occurs due to server problems with date values. 
Moved to API project.

**Comment by ernado-x** [comment]
Server should not know about clients UI. From API we only get date. Formatting dates is responsibility of 'View' layer on client.

**Comment by floring** [comment]
@ernado-x , I agree with you. But in this case server already returns wrong date values due to parsing reasons. This part "T00:00:00" is incorrect. 
Fixed.
