### ISSUE TITLE
Problem with date placement

### ISSUE THREAD

**Issue by DenysMorgun** [kpi-ua/ecampus-client-android#54]
The problem occurs only in the moderator's mode.
![screenshot_2016-06-23-12-37-34](https://cloud.githubusercontent.com/assets/18088574/16300447/a94972e0-3948-11e6-81bd-61ea87fdec6c.png)
![screenshot_2016-06-23-12-45-29](https://cloud.githubusercontent.com/assets/18088574/16300473/cb8c697a-3948-11e6-9e1d-e44eb103a892.png)
Device: HTC Desire 516.
OS: Android 4.3

**Comment by floring** [comment]
Fixed in 958abe1f7145d49dc06f0bbd907c7c6ead196434.
