### ISSUE TITLE
Bug in AddBulletinActivity, button "more"

### ISSUE THREAD

**Issue by Lewiy** [kpi-ua/ecampus-client-android#62]
Bug in AddBulletinActivity, when the full name is too large
![screenshot_20160708-104302 1](https://cloud.githubusercontent.com/assets/15640162/16681171/caebfb48-44fb-11e6-890b-06a0aa33419d.png)

**Comment by floring** [comment]
Fixed in 5696210e660400e4fc2bce5fab0739fb46683256
