### ISSUE TITLE
Implement calendar for authorized users

### ISSUE THREAD

**Issue by ernado-x** [kpi-ua/ecampus-client-android#7]
API:  http://campus-api.azurewebsites.net/Calendar 

Usage example:
* Create new record: [GET] http://campus-api.azurewebsites.net/Calendar/AddNewPlanner?sessionId=656b94bb-0a81-4052-9ded-17d3be4e26ea&date=10.01.2015&title=TestTitle&time=00:10&task=Test%20description
* Load user records: GET] http://campus-api.azurewebsites.net/Calendar/GetAllForUserDate?sessionId=656b94bb-0a81-4052-9ded-17d3be4e26ea&date=10.01.2015&actuality=1&page=1

**Comment by doroshartyom** [comment]
Will be implemented on second milestone.
